// <auto-generated />
using System;
using DefinitiveChallenge.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DefinitiveChallenge.API.Migrations
{
    [DbContext(typeof(ProductInfoContext))]
    partial class ProductInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("DefinitiveChallenge.API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BuyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuyDate = new DateTime(2022, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Automovil Twingo",
                            State = true,
                            Type = "Vehículos",
                            Value = 20000000.0
                        },
                        new
                        {
                            Id = 2,
                            BuyDate = new DateTime(2022, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Finca con piscina, salón de juegos, patio, cuarto de cocina, cuarto de ropas y 8 habitaciones",
                            State = false,
                            Type = "Bienes",
                            Value = 400000000.0
                        },
                        new
                        {
                            Id = 3,
                            BuyDate = new DateTime(2022, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Telefono móvil iphone 14",
                            State = true,
                            Type = "Bienes",
                            Value = 5487599.9900000002
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
